### ISSUE TITLE
Project doesn't build

### ISSUE THREAD

**Issue by rfringuello89** [hmzdtz/android-systemui#1]
Hello!
I tried to open this project with Android Studio, as soon as I  run the build I get several build errors due to:
- ERROR: android.window.IOnBackInvokedCallback: couldn't find import for class android.window.IOnBackInvokedCallback
- Task :packageDebugResources FAILED   due to a lot of resources found more than one time
- ..

Am I missing any preliminary steps to do?!

Regards,

**Comment by hmzdtz** [comment]
**This is an unfinished version**. I've decided to abandon the attempt to compile SystemUI independently on Android Studio, and I also don't recommend separating SystemUI.

Here's the situation: I successfully separated the SystemUI from the Android 13 source code provided by MTK for MTK8188 in an internal project at my company, and imported it into Android Studio. I wanted to create a more universal SystemUI, so I created this repository and completed part of it. However, later on, I found that SystemUI is tightly coupled with the system, relying on many private resources and interfaces. This leads to issues like the following examples:

1. For instance, there is a dedicated management class in the system for handling status bar height-related issues. This class is not within SystemUI. SystemUI cannot override the data provided by this class, because SystemUI is only responsible for displaying. Otherwise, there is inconsistency between the status bar height obtained by other modules (like Launcher3) and the actual height displayed by SystemUI.
2. Then, handling these resource conflicts is really troublesome, and the private resources in different major versions of Android may change significantly, making it difficult to establish a universal SystemUI with consistent functionality compared to the native SystemUI.
3. During independent compilation in Android Studio, aapt2 may generate resource IDs for private resources like `@*android:` that do not match those in the internal system (because customized android system may add some custom resources or remove some resources, resulting in resource ID reordering on the device). This mismatch can lead to runtime exceptions. In actual projects, I replaced all `@*android:` resources in SystemUI with fixed values copied from other parts of the framework.
4. Additionally, when the system source code changes, it's necessary to regenerate `android.jar` from the compiled product of framework and replace the android.jar in the SDK with it (you can use `bootstrapClasspath` configuration in gradle to add your own android.jar to the class loading order).

Therefore, unless it's necessary to hand over SystemUI to a large team that cannot access the complete system source code, and the target Android major version is relatively stable, **I do not recommend build SystemUI with gradle independently**.

**Comment by rfringuello89** [comment]
Same for me.. really hard to get this working..

**Comment by hmzdtz** [comment]
I succeeded once in the project, at that time the company provided me with equipment that couldn't compile the whole framework. But since I was assigned a more powerful desktop PC, I found that doing so didn't make much sense anymore.

**Comment by rfringuello89** [comment]
Well, it's more for having the preview of xml files.. is it possible to
have it in any way?

Il mar 6 feb 2024, 13:04 会码字的兔子 ***@***.***> ha scritto:

**Comment by rfringuello89** [comment]
But I suppose that without the resources, jar, internals and so on also the preview will be very limited

**Comment by hmzdtz** [comment]
The version I successfully compiled before still can't preview the internal XML resources I used. **This is not related to compilation, but to Android Studio's inability to recognize these identifiers**, so it can't resolve the problem.

**Unless you replace all internal resources with your own defined resources**. Speaking of which, I can provide you with an idea: **you can create a flavor and a completely new resource directory, rewrite these resources inside it, and select this flavor in Android Studio.** This way, since the new directory you added is not written in the Android.bp file, it won't affect the mm compilation, but only affect Android Studio's indexing. Later, when you need to preview the resources, you just need to copy this file to the corresponding resource file of your flavor, replace the internal resources, and this will solve the problem (note that after editing the resource file, you need to write the effective changes to the file in the SystemUI project's own resource directory). Because this flavor is for Android Studio to see, not for the system compilation toolchain to see.

**Comment by rfringuello89** [comment]
Yes, more or less my same idea.. problem is the framework/red stuff that contains a lot of doubled resources  :/ didn't figure out if there is a good way to export an aar from build output that can be used in Studio instead of taking all the resources and modify by hand

**Comment by amedfa** [comment]
For those that like AStudio, and want to develop for AOSP, you can give a try to https://developer.android.com/studio/platform

or if SystemUI is your single project, why not using the Plugins  [here](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/packages/SystemUI/docs/plugins.md#writing-plugins) 
or creating your own "SystemUI" as what CarSystemUI  or TVSystemUI does like [here](https://www.tomesoftware.com/labs/customizing-androids-systemui/)

@hmzdtz I'm testing the idea to overlay some settings on the aosp to replace some layout regard to navigation bar and 
using the plugin OverlayPlugin like [here](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/packages/SystemUI/plugin/ExamplePlugin/src/com/android/systemui/plugin/testoverlayplugin/SampleOverlayPlugin.java#63)  to run the project from AStudio and do some quick test without using `mm` from the aosp source code
do you have any advise on this?

**Comment by hmzdtz** [comment]
@amedfa My requirement was to independently compile SystemUI in Android Studio without depending on other system components, especially without relying on any other system source code or resources. Since not everyone in our team has a powerful computer, and most of them use MacOS, we need to split SystemUI so that it's easier for others to maintain. 

Additionally, I don't have much knowledge about OverlayPlugin. I've since transitioned to backend development, so I haven't been involved in Android much.
